#!/bin/bash
set -e

echo "=========================================="
echo "Publishing Firefox to Flatpak registry"
echo "=========================================="

REGISTRY="http://flatpak-registry:8080"
TARBALL="/home/builder/output/firefox.tar.xz"

# Wait for registry to be available
timeout 60 bash -c 'until curl -s http://flatpak-registry:8080/ > /dev/null; do sleep 1; done'

# Extract tarball
EXTRACT_DIR="/tmp/firefox-flatpak-extract"
mkdir -p "${EXTRACT_DIR}"
echo "Extracting Firefox tarball..."
tar -xf "${TARBALL}" -C "${EXTRACT_DIR}"

# Initialize flatpak build directory for Firefox
echo "Initializing Firefox Flatpak build..."
flatpak build-init /tmp/firefox-flatpak org.mozilla.firefox \
    org.freedesktop.Sdk org.freedesktop.Platform 23.08

# Create directory structure inside the flatpak
mkdir -p /tmp/firefox-flatpak/files/lib/firefox
mkdir -p /tmp/firefox-flatpak/files/bin

# Copy Firefox files into the flatpak
echo "Copying Firefox files into Flatpak structure..."
cp -a "${EXTRACT_DIR}/firefox/." /tmp/firefox-flatpak/files/lib/firefox/

# Include geckodriver
cp /home/builder/output/geckodriver /tmp/firefox-flatpak/files/lib/firefox/geckodriver
chmod +x /tmp/firefox-flatpak/files/lib/firefox/geckodriver
ln -sf /app/lib/firefox/geckodriver /tmp/firefox-flatpak/files/bin/geckodriver

# Create launcher script (mirrors firefox/browser/installer/linux/app/flatpak/files/bin/firefox)
cat > /tmp/firefox-flatpak/files/bin/firefox << 'LAUNCHER'
#!/bin/bash
export TMPDIR="${XDG_CACHE_HOME:-$HOME/.cache}/tmp"
exec /app/lib/firefox/firefox --name org.mozilla.firefox "$@"
LAUNCHER
chmod +x /tmp/firefox-flatpak/files/bin/firefox

# Finish the build with browser-appropriate permissions.
# Note: BaseApp (org.mozilla.firefox.BaseApp) is skipped for this test packaging.
# Firefox will install but requires BaseApp to run.
flatpak build-finish /tmp/firefox-flatpak \
    --command=firefox \
    --share=ipc \
    --share=network \
    --socket=pulseaudio \
    --socket=wayland \
    --socket=fallback-x11 \
    --socket=session-bus \
    --filesystem=xdg-download

# Export to the existing OSTree repo (/tmp/flatpak-repo already has access-keys).
# The GPG key flatpak@test.local was generated by publish-flatpak.sh and is
# still in the keyring, so we can reuse it directly.
echo "Exporting Firefox to Flatpak repository..."
flatpak build-export --gpg-sign=flatpak@test.local /tmp/flatpak-repo \
    /tmp/firefox-flatpak stable

# Regenerate signed summary (now covers both access-keys and Firefox)
flatpak build-update-repo --gpg-sign=flatpak@test.local /tmp/flatpak-repo

# Upload all repository contents as a single tarball
echo "Uploading repository as tarball..."
cd /tmp/flatpak-repo
tar -czf /tmp/flatpak-repo-update.tar.gz .
curl --upload-file /tmp/flatpak-repo-update.tar.gz \
    "${REGISTRY}/flatpak-repo/repo-update.tar.gz"

# Wait for registry to extract (tarball disappears when done)
echo "Waiting for registry to extract..."
timeout 120 bash -c 'while curl -s -o /dev/null -w "%{http_code}" \
    http://flatpak-registry:8080/flatpak-repo/repo-update.tar.gz | grep -q 200; do sleep 2; done'

echo "Firefox Flatpak publish complete"
echo ""
